#
# Enable or disable the plugin. This will be effect when reload or restart the server.
#
enable: true

indicator:
  # Format for displaying in indicators

  #
  # You can generate your own format below:
  # https://www.birdflop.com/resources/rgb/
  # select Color format to MiniMessage
  #

  # {mobname} is the name of the entity
  # {healamount} is the amount of health restored
  # {currenthealth} is the current health of the entity
  # {maxhealth} is the maximum health of the entity
  health-indicator-format: "<aqua>+{healamount}</aqua> <green>[{currenthealth}/{maxhealth}❤]</green>"

  # {mobname} is the name of the entity
  # {damage} is the amount of damage dealt
  # {currenthealth} is the current health of the entity
  # {maxhealth} is the maximum health of the entity
  damage-indicator-format: "<red>-{damage}</red> <green>[{currenthealth}/{maxhealth}❤]</green>"
  critical-damage-indicator-format: "<gold><b>✧</b></gold> <red>-{damage}</red> <green>[{currenthealth}/{maxhealth}❤]</green>"


  # The lifetime of the indicators in ticks before they disappear
  # must be greater than 1
  lifetime: 12

# List of entities and worlds to ignore
blacklist:
  # This will not show any indicators for these entities
  # You can add more entities to this list
  entities:
    - "item_frame"
    - "item" # Dropped items

  # List of worlds to ignore
  worlds:
    - "world_example"